### ISSUE TITLE
Implement Flight Inventory Table changes

### ISSUE THREAD

**Issue by brandonhundt** [PRX/grove.prx.org#137]
This is a fix for the flights in progress issue. If this feels too large for one ticket, feel free to break it up.

Sketch file: https://sketch.cloud/s/WlAj8/a/L81O73

![Screen Shot 2020-02-27 at 1.15.18 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/17d536a5-e266-4b57-ad6d-1f4e8ca7e4bb)

- [x] Roll up all zones into a single table (TODO in #170)
- [ ] Status "chip". Text reflects the flight progress (Hold, In progress, Cancelled, etc) Background color represents how well the flight is performing. 

Availability:
- [x] Zero out when the date has passed. Totals include only the remaining values.

Allocated:
- [x] Rename Goal to Allocated
- [x] Dates in the past are bolded and light gray
- [x] If showing preview, add `*`

Actuals:
- [x] Dates in the past are bolded and light gray

Color Notes:
- [ ] Orange dashed border line represents a week with an episode drop (If expanded this should show update to the day) -- If challenging I can take or leave it (TODO in #169)
- [x] Blue border line represents the current date (If expanded, should follow the current date)
- [x] Use red text if the flight is borked and requires manual intervention (TODO in #168)

Expanded:
[Screen Shot 2020-02-27 at 1.57.27 PM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/e9a99267-1d69-454b-bfb1-9ce688de0a66)

**Comment by sandikbarr** [comment]
@brandonhundt These are Campaign Status values:
| Status "chip". Text reflects the flight progress (Hold, In progress, Cancelled, etc)
You want this campaign status shown on each flight's inventory table? Or did you want the flight status ("Ok" or "Error")?

**Comment by sandikbarr** [comment]
To show some sort of indicator when the unsaved preview is shown as opposed to the allocated amount, it uses the color green and an asterisk(*) on the allocations column. How should preview be indicated in the new design?

**Comment by sandikbarr** [comment]
> Use red text if the flight is borked and requires manual intervention

What does this mean more mathematical terms?
Currently, a row would be highlighted red if the allocation preview > allocated + available, or if on allocation preview the Allocated column > Available column.

**Comment by brandonhundt** [comment]
1. What I'm hoping to achieve is that the chip label reflects the campaign state (Hold, In progress, etc). The color of the chip reflects the status (Ok = green, Error = Red)

2. Good catch, the asterisk should remain for unsaved flight data.

3. [Use red text if the flight is borked and requires manual intervention]: I think your math is correct, might want to run it by @ryan just to confirm.
